[build]
command = "npm run build"
publish = "dist/public"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"

[functions]
directory = "netlify/functions-build"
node_bundler = "esbuild"
external_node_modules = ["express", "multer", "passport", "passport-local", "express-session", "connect-pg-simple"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev"
port = 5000
targetPort = 5000
framework = "vite" 